version: '3'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - /run/desktop/mnt/host/d/PROGRAMACION/CURSOS/CURSOS-UDEMY/ANGULAR/FERNANDO-HERRERA/angular/12-nest-backend/mongo:/data/db
    ports:
      - 27017:27017
    restart: always
